### ISSUE TITLE
Can't install openai package

### ISSUE THREAD

**Issue by joseph-farruggio** [joseph-farruggio/create-acf-block-cli#1]
What I've done:

`composer require openai-php/laravel`
`php create-acf-block openai:install`

The last command results in `No arguments expected, got "openai:install".`

**Comment by ProjektGopher** [comment]
I think you could add `OpenAI\Laravel\Commands\InstallCommand::class` to `config/commands.php` in the `hidden` property to get this installed, but I think you'd have a better time integrating the base `openai-php/client` package instead, which is what `openai-php/laravel` wraps. It's not actually that hard, but I could set aside like an hour to pair on it tomorrow if you like.

**Comment by joseph-farruggio** [comment]
This is what I get when I add the command class to `config/commands.php` within `hidden`:

<img width="1320" alt="image" src="https://github.com/joseph-farruggio/create-acf-block-cli/assets/18406430/d9f1c55f-d00f-4355-b89e-78a75dc50253">

**Comment by ProjektGopher** [comment]
Resolved
